# This workflow will deploy the current code to Heroku

name: Continuous Deployment

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "jansonsa-sem1"
          heroku_email: "jansonsa@uni.coventry.ac.uk"
